version: '3.7'
services:
  django-app:
    image: amitkmr076/react_django_demo_app:latest
    ports:
      - "8000:8000"
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test@123

